### ISSUE TITLE
Build of 2024.12.26 aborts with error

### ISSUE THREAD

**Issue by makoONE** [bbaa-bbaa/i915-sriov-dkms#14]
My attempts to build the latest dkms module 2024.12.26 on proxmox abort with an error. Please see attached logfile.
[make.log](https://github.com/user-attachments/files/18259544/make.log)

**Comment by bbaa-bbaa** [comment]
try [2024.12.27](https://github.com/bbaa-bbaa/i915-sriov-dkms/commit/01b0dc91862cebe0fcb215619df2cf886d1a7808)

**Comment by makoONE** [comment]
same as before
[make.log](https://github.com/user-attachments/files/18260246/make.log)

**Comment by bbaa-bbaa** [comment]
Thanks for your test.
It seems that there are still incorrect patch selections breaking the 6.11 kernel.
Try https://github.com/bbaa-bbaa/i915-sriov-dkms/commit/4a82c9c4a2013ebabf60d3a356a215a1f53e63ad

**Comment by makoONE** [comment]
thanks, it builds flawlessly again.
