### ISSUE TITLE
Failed to run intel_gpu_top

### ISSUE THREAD

**Issue by wzhy19** [bbaa-bbaa/i915-sriov-dkms#6]
```
Failed to detect engines! (No such file or directory)
(Kernel 4.16 or newer is required for i915 PMU support.)
```

Maybe need some more modules to work
Linux Mint 22 6.8.0-49-generic #49-Ubuntu SMP PREEMPT_DYNAMIC

**Comment by bbaa-bbaa** [comment]
It seems that PMU currently only supports PF. You can use `intel_gpu_top -d sys:/sys/devices/pci0000:00/0000:00:02.0` to view the top on the host GPU
