### ISSUE TITLE
*ERROR* GT0: GUC: mmio request 0x4100: failure 201/0 all version i915-sriov-dkms

### ISSUE THREAD

**Issue by sacredx72** [bbaa-bbaa/i915-sriov-dkms#9]
Good afternoon, I wanted to ask a question and ask for help in solving the problem with errors in the logs that prevent the use of SR-IOV in VM and LXC
I installed your latest version 2024.12.02. Installation went without errors, after reboot I provide an error log
root@server:~# dmesg | grep i915
[    0.000000] Command line: initrd=\EFI\proxmox\6.8.12-4-pve\initrd.img-6.8.12-4-pve root=ZFS=rpool/ROOT/pve-1 boot=zfs intel_iommu=on pcie_aspm=force pcie_aspm.policy=powersave i915.enable_guc=3 i915.max_vfs=7 module_blacklist=xe
[    0.072873] Kernel command line: initrd=\EFI\proxmox\6.8.12-4-pve\initrd.img-6.8.12-4-pve root=ZFS=rpool/ROOT/pve-1 boot=zfs intel_iommu=on pcie_aspm=force pcie_aspm.policy=powersave i915.enable_guc=3 i915.max_vfs=7 module_blacklist=xe
[   17.461469] i915: module verification failed: signature and/or required key missing - tainting kernel
[   17.859335] i915 0000:00:02.0: Running in SR-IOV PF mode
[   17.860059] i915 0000:00:02.0: [drm] VT-d active for gfx access
[   17.860089] i915 0000:00:02.0: vgaarb: deactivate vga console
[   17.860194] i915 0000:00:02.0: [drm] Using Transparent Hugepages
[   17.860769] i915 0000:00:02.0: vgaarb: VGA decodes changed: olddecodes=io+mem,decodes=none:owns=io+mem
[   17.875720] i915 0000:00:02.0: [drm] Finished loading DMC firmware i915/adlp_dmc.bin (v2.20)
[   17.882143] i915 0000:00:02.0: [drm] GT0: GuC firmware i915/adlp_guc_70.bin version 70.36.0
[   17.882149] i915 0000:00:02.0: [drm] GT0: HuC firmware i915/tgl_huc.bin version 7.9.3
[   17.885442] i915 0000:00:02.0: [drm] GT0: HuC: authenticated for all workloads
[   17.885917] i915 0000:00:02.0: [drm] GT0: GUC: submission enabled
[   17.885918] i915 0000:00:02.0: [drm] GT0: GUC: SLPC enabled
[   17.886419] i915 0000:00:02.0: [drm] GT0: GUC: RC enabled
[   17.886553] i915 0000:00:02.0: [drm] *ERROR* GT0: GUC: mmio request 0x4100: failure 201/0
[   17.886557] i915 0000:00:02.0: [drm] *ERROR* GT0: Failed to retrieve hwconfig table: -ENOENT
[   17.889102] i915 0000:00:02.0: [drm] Protected Xe Path (PXP) protected content support initialized
[   17.890258] [drm] Initialized i915 1.6.0 20201103 for 0000:00:02.0 on minor 0
[   17.892490] i915 display info: display version: 13
[   17.892492] i915 display info: cursor_needs_physical: no
[   17.892493] i915 display info: has_cdclk_crawl: yes
[   17.892494] i915 display info: has_cdclk_squash: no
[   17.892495] i915 display info: has_ddi: yes
[   17.892496] i915 display info: has_dp_mst: yes
[   17.892497] i915 display info: has_dsb: yes
[   17.892498] i915 display info: has_fpga_dbg: yes
[   17.892499] i915 display info: has_gmch: no
[   17.892500] i915 display info: has_hotplug: yes
[   17.892501] i915 display info: has_hti: no
[   17.892502] i915 display info: has_ipc: yes
[   17.892503] i915 display info: has_overlay: no
[   17.892503] i915 display info: has_psr: yes
[   17.892504] i915 display info: has_psr_hw_tracking: no
[   17.892505] i915 display info: overlay_needs_physical: no
[   17.892506] i915 display info: supports_tv: no
[   17.892507] i915 display info: has_hdcp: yes
[   17.892508] i915 display info: has_dmc: yes
[   17.892509] i915 display info: has_dsc: yes
[   17.892604] i915 0000:00:02.0: [drm] Cannot find any crtc or sizes
[   17.892652] i915 0000:00:02.0: 7 VFs could be associated with this PF
[   17.892739] i915 0000:00:02.0: [drm] Cannot find any crtc or sizes
[   17.892830] i915 0000:00:02.0: [drm] Cannot find any crtc or sizes
[   17.892741] snd_hda_intel 0000:00:1f.3: bound 0000:00:02.0 (ops i915_audio_component_bind_ops [i915])
[   23.411137] i915 0000:00:02.0: vgaarb: VGA decodes changed: olddecodes=none,decodes=none:owns=io+mem
[   23.411263] i915 0000:00:02.1: enabling device (0000 -> 0002)
[   23.411345] i915 0000:00:02.1: Running in SR-IOV VF mode
[   23.412012] i915 0000:00:02.1: [drm] GT0: GUC: interface version 0.1.17.0
[   23.413801] i915 0000:00:02.1: [drm] VT-d active for gfx access
[   23.413838] i915 0000:00:02.1: [drm] Using Transparent Hugepages
[   23.414381] i915 0000:00:02.1: [drm] GT0: GUC: interface version 0.1.17.0
[   23.415007] i915 0000:00:02.1: [drm] GT0: GUC: interface version 0.1.17.0
[   23.416289] i915 0000:00:02.1: GuC firmware PRELOADED version 0.0 submission:SR-IOV VF
[   23.416307] i915 0000:00:02.1: HuC firmware PRELOADED
[   23.417067] i915 0000:00:02.1: [drm] *ERROR* GT0: GUC: mmio request 0x4100: failure 201/0
[   23.417070] i915 0000:00:02.1: [drm] *ERROR* GT0: Failed to retrieve hwconfig table: -ENOENT
[   23.420373] i915 0000:00:02.1: [drm] Protected Xe Path (PXP) protected content support initialized
[   23.420383] i915 0000:00:02.1: [drm] PMU not supported for this GPU.
[   23.420553] [drm] Initialized i915 1.6.0 20201103 for 0000:00:02.1 on minor 1
[   23.421127] i915 0000:00:02.0: vgaarb: VGA decodes changed: olddecodes=none,decodes=none:owns=io+mem
[   23.421132] i915 0000:00:02.1: vgaarb: VGA decodes changed: olddecodes=io+mem,decodes=none:owns=none
[   23.421203] i915 0000:00:02.2: enabling device (0000 -> 0002)
[   23.421238] i915 0000:00:02.2: Running in SR-IOV VF mode
[   23.421913] i915 0000:00:02.2: [drm] GT0: GUC: interface version 0.1.17.0
[   23.422945] i915 0000:00:02.2: [drm] VT-d active for gfx access
[   23.422963] i915 0000:00:02.2: [drm] Using Transparent Hugepages
[   23.423488] i915 0000:00:02.2: [drm] GT0: GUC: interface version 0.1.17.0
[   23.424011] i915 0000:00:02.2: [drm] GT0: GUC: interface version 0.1.17.0
[   23.424731] i915 0000:00:02.2: GuC firmware PRELOADED version 0.0 submission:SR-IOV VF
[   23.424734] i915 0000:00:02.2: HuC firmware PRELOADED
[   23.425224] i915 0000:00:02.2: [drm] *ERROR* GT0: GUC: mmio request 0x4100: failure 201/0
[   23.425228] i915 0000:00:02.2: [drm] *ERROR* GT0: Failed to retrieve hwconfig table: -ENOENT
[   23.427669] i915 0000:00:02.2: [drm] Protected Xe Path (PXP) protected content support initialized
[   23.427675] i915 0000:00:02.2: [drm] PMU not supported for this GPU.
[   23.427755] [drm] Initialized i915 1.6.0 20201103 for 0000:00:02.2 on minor 2
[   23.428154] i915 0000:00:02.0: vgaarb: VGA decodes changed: olddecodes=none,decodes=none:owns=io+mem
[   23.428158] i915 0000:00:02.1: vgaarb: VGA decodes changed: olddecodes=none,decodes=none:owns=none
[   23.428162] i915 0000:00:02.2: vgaarb: VGA decodes changed: olddecodes=io+mem,decodes=none:owns=none
[   23.428211] i915 0000:00:02.3: enabling device (0000 -> 0002)
[   23.428244] i915 0000:00:02.3: Running in SR-IOV VF mode
[   23.428789] i915 0000:00:02.3: [drm] GT0: GUC: interface version 0.1.17.0
[   23.429277] i915 0000:00:02.3: [drm] VT-d active for gfx access
[   23.429293] i915 0000:00:02.3: [drm] Using Transparent Hugepages
[   23.429946] i915 0000:00:02.3: [drm] GT0: GUC: interface version 0.1.17.0
[   23.430460] i915 0000:00:02.3: [drm] GT0: GUC: interface version 0.1.17.0
[   23.431505] i915 0000:00:02.3: GuC firmware PRELOADED version 0.0 submission:SR-IOV VF
[   23.431523] i915 0000:00:02.3: HuC firmware PRELOADED
[   23.431779] i915 0000:00:02.3: [drm] *ERROR* GT0: GUC: mmio request 0x4100: failure 201/0
[   23.431786] i915 0000:00:02.3: [drm] *ERROR* GT0: Failed to retrieve hwconfig table: -ENOENT
[   23.434617] i915 0000:00:02.3: [drm] Protected Xe Path (PXP) protected content support initialized
[   23.434649] i915 0000:00:02.3: [drm] PMU not supported for this GPU.
[   23.434756] [drm] Initialized i915 1.6.0 20201103 for 0000:00:02.3 on minor 3
[   23.435188] i915 0000:00:02.0: vgaarb: VGA decodes changed: olddecodes=none,decodes=none:owns=io+mem
[   23.435194] i915 0000:00:02.1: vgaarb: VGA decodes changed: olddecodes=none,decodes=none:owns=none
[   23.435198] i915 0000:00:02.2: vgaarb: VGA decodes changed: olddecodes=none,decodes=none:owns=none
[   23.435203] i915 0000:00:02.3: vgaarb: VGA decodes changed: olddecodes=io+mem,decodes=none:owns=none
[   23.435258] i915 0000:00:02.4: enabling device (0000 -> 0002)
[   23.435294] i915 0000:00:02.4: Running in SR-IOV VF mode
[   23.435505] i915 0000:00:02.4: [drm] GT0: GUC: interface version 0.1.17.0
[   23.436031] i915 0000:00:02.4: [drm] VT-d active for gfx access
[   23.436061] i915 0000:00:02.4: [drm] Using Transparent Hugepages
[   23.436235] i915 0000:00:02.4: [drm] GT0: GUC: interface version 0.1.17.0
[   23.436709] i915 0000:00:02.4: [drm] GT0: GUC: interface version 0.1.17.0
[   23.437399] i915 0000:00:02.4: GuC firmware PRELOADED version 0.0 submission:SR-IOV VF
[   23.437407] i915 0000:00:02.4: HuC firmware PRELOADED
[   23.437680] i915 0000:00:02.4: [drm] *ERROR* GT0: GUC: mmio request 0x4100: failure 201/0
[   23.437685] i915 0000:00:02.4: [drm] *ERROR* GT0: Failed to retrieve hwconfig table: -ENOENT
[   23.444078] i915 0000:00:02.4: [drm] Protected Xe Path (PXP) protected content support initialized
[   23.444085] i915 0000:00:02.4: [drm] PMU not supported for this GPU.
[   23.444161] [drm] Initialized i915 1.6.0 20201103 for 0000:00:02.4 on minor 4
[   23.444718] i915 0000:00:02.0: vgaarb: VGA decodes changed: olddecodes=none,decodes=none:owns=io+mem
[   23.444723] i915 0000:00:02.1: vgaarb: VGA decodes changed: olddecodes=none,decodes=none:owns=none
[   23.444728] i915 0000:00:02.2: vgaarb: VGA decodes changed: olddecodes=none,decodes=none:owns=none
[   23.444733] i915 0000:00:02.3: vgaarb: VGA decodes changed: olddecodes=none,decodes=none:owns=none
[   23.444738] i915 0000:00:02.4: vgaarb: VGA decodes changed: olddecodes=io+mem,decodes=none:owns=none
[   23.444860] i915 0000:00:02.5: enabling device (0000 -> 0002)
[   23.444903] i915 0000:00:02.5: Running in SR-IOV VF mode
[   23.445163] i915 0000:00:02.5: [drm] GT0: GUC: interface version 0.1.17.0
[   23.445965] i915 0000:00:02.5: [drm] VT-d active for gfx access
[   23.446002] i915 0000:00:02.5: [drm] Using Transparent Hugepages
[   23.446228] i915 0000:00:02.5: [drm] GT0: GUC: interface version 0.1.17.0
[   23.446985] i915 0000:00:02.5: [drm] GT0: GUC: interface version 0.1.17.0
[   23.447735] i915 0000:00:02.5: GuC firmware PRELOADED version 0.0 submission:SR-IOV VF
[   23.447739] i915 0000:00:02.5: HuC firmware PRELOADED
[   23.448002] i915 0000:00:02.5: [drm] *ERROR* GT0: GUC: mmio request 0x4100: failure 201/0
[   23.448007] i915 0000:00:02.5: [drm] *ERROR* GT0: Failed to retrieve hwconfig table: -ENOENT
[   23.451055] i915 0000:00:02.5: [drm] Protected Xe Path (PXP) protected content support initialized
[   23.451064] i915 0000:00:02.5: [drm] PMU not supported for this GPU.
[   23.451177] [drm] Initialized i915 1.6.0 20201103 for 0000:00:02.5 on minor 5
[   23.451904] i915 0000:00:02.0: vgaarb: VGA decodes changed: olddecodes=none,decodes=none:owns=io+mem
[   23.451909] i915 0000:00:02.1: vgaarb: VGA decodes changed: olddecodes=none,decodes=none:owns=none
[   23.451913] i915 0000:00:02.2: vgaarb: VGA decodes changed: olddecodes=none,decodes=none:owns=none
[   23.451916] i915 0000:00:02.3: vgaarb: VGA decodes changed: olddecodes=none,decodes=none:owns=none
[   23.451920] i915 0000:00:02.4: vgaarb: VGA decodes changed: olddecodes=none,decodes=none:owns=none
[   23.451924] i915 0000:00:02.5: vgaarb: VGA decodes changed: olddecodes=io+mem,decodes=none:owns=none
[   23.451968] i915 0000:00:02.6: enabling device (0000 -> 0002)
[   23.451995] i915 0000:00:02.6: Running in SR-IOV VF mode
[   23.452227] i915 0000:00:02.6: [drm] GT0: GUC: interface version 0.1.17.0
[   23.452905] i915 0000:00:02.6: [drm] VT-d active for gfx access
[   23.452939] i915 0000:00:02.6: [drm] Using Transparent Hugepages
[   23.453114] i915 0000:00:02.6: [drm] GT0: GUC: interface version 0.1.17.0
[   23.453806] i915 0000:00:02.6: [drm] GT0: GUC: interface version 0.1.17.0
[   23.454934] i915 0000:00:02.6: GuC firmware PRELOADED version 0.0 submission:SR-IOV VF
[   23.454942] i915 0000:00:02.6: HuC firmware PRELOADED
[   23.455339] i915 0000:00:02.6: [drm] *ERROR* GT0: GUC: mmio request 0x4100: failure 201/0
[   23.455347] i915 0000:00:02.6: [drm] *ERROR* GT0: Failed to retrieve hwconfig table: -ENOENT
[   23.458162] i915 0000:00:02.6: [drm] Protected Xe Path (PXP) protected content support initialized
[   23.458169] i915 0000:00:02.6: [drm] PMU not supported for this GPU.
[   23.458339] [drm] Initialized i915 1.6.0 20201103 for 0000:00:02.6 on minor 6
[   23.458739] i915 0000:00:02.0: vgaarb: VGA decodes changed: olddecodes=none,decodes=none:owns=io+mem
[   23.458744] i915 0000:00:02.1: vgaarb: VGA decodes changed: olddecodes=none,decodes=none:owns=none
[   23.458749] i915 0000:00:02.2: vgaarb: VGA decodes changed: olddecodes=none,decodes=none:owns=none
[   23.458754] i915 0000:00:02.3: vgaarb: VGA decodes changed: olddecodes=none,decodes=none:owns=none
[   23.458759] i915 0000:00:02.4: vgaarb: VGA decodes changed: olddecodes=none,decodes=none:owns=none
[   23.458764] i915 0000:00:02.5: vgaarb: VGA decodes changed: olddecodes=none,decodes=none:owns=none
[   23.458768] i915 0000:00:02.6: vgaarb: VGA decodes changed: olddecodes=io+mem,decodes=none:owns=none
[   23.458823] i915 0000:00:02.7: enabling device (0000 -> 0002)
[   23.458854] i915 0000:00:02.7: Running in SR-IOV VF mode
[   23.459185] i915 0000:00:02.7: [drm] GT0: GUC: interface version 0.1.17.0
[   23.459820] i915 0000:00:02.7: [drm] VT-d active for gfx access
[   23.459846] i915 0000:00:02.7: [drm] Using Transparent Hugepages
[   23.460010] i915 0000:00:02.7: [drm] GT0: GUC: interface version 0.1.17.0
[   23.460544] i915 0000:00:02.7: [drm] GT0: GUC: interface version 0.1.17.0
[   23.461214] i915 0000:00:02.7: GuC firmware PRELOADED version 0.0 submission:SR-IOV VF
[   23.461217] i915 0000:00:02.7: HuC firmware PRELOADED
[   23.461512] i915 0000:00:02.7: [drm] *ERROR* GT0: GUC: mmio request 0x4100: failure 201/0
[   23.461515] i915 0000:00:02.7: [drm] *ERROR* GT0: Failed to retrieve hwconfig table: -ENOENT
[   23.464931] i915 0000:00:02.7: [drm] Protected Xe Path (PXP) protected content support initialized
[   23.464935] i915 0000:00:02.7: [drm] PMU not supported for this GPU.
[   23.464994] [drm] Initialized i915 1.6.0 20201103 for 0000:00:02.7 on minor 7
[   23.465189] i915 0000:00:02.0: Enabled 7 VFs
[  102.289605] i915 0000:00:02.0: VF4 FLR
[  104.044140] i915 0000:00:02.0: VF4 FLR
[  104.185779] i915 0000:00:02.0: VF4 FLR
[  184.772303] i915 0000:00:02.0: [drm] *ERROR* GT0: GUC: CT: Sending action 0x550b failed (-EIO) status=0XE0000102
[  184.772317] i915 0000:00:02.0: [drm] GT0: IOV: Failed to save VF1 state (-EPROTO)
[  184.772586] i915 0000:00:02.0: [drm] *ERROR* GT0: GUC: CT: Sending action 0x550b failed (-EIO) status=0XE0000102
[  184.772591] i915 0000:00:02.0: [drm] GT0: IOV: Failed to save VF2 state (-EPROTO)
[  184.772782] i915 0000:00:02.0: [drm] *ERROR* GT0: GUC: CT: Sending action 0x550b failed (-EIO) status=0XE0000102
[  184.772785] i915 0000:00:02.0: [drm] GT0: IOV: Failed to save VF3 state (-EPROTO)
[  184.772946] i915 0000:00:02.0: [drm] *ERROR* GT0: GUC: CT: Sending action 0x550b failed (-EIO) status=0XE000000A
[  184.772949] i915 0000:00:02.0: [drm] GT0: IOV: Failed to save VF4 state (-EPROTO)
[  184.773313] i915 0000:00:02.0: [drm] *ERROR* GT0: GUC: CT: Sending action 0x550b failed (-EIO) status=0XE0000102
[  184.773316] i915 0000:00:02.0: [drm] GT0: IOV: Failed to save VF5 state (-EPROTO)
[  184.773701] i915 0000:00:02.0: [drm] *ERROR* GT0: GUC: CT: Sending action 0x550b failed (-EIO) status=0XE0000102
[  184.773704] i915 0000:00:02.0: [drm] GT0: IOV: Failed to save VF6 state (-EPROTO)
[  184.773964] i915 0000:00:02.0: [drm] *ERROR* GT0: GUC: CT: Sending action 0x550b failed (-EIO) status=0XE0000102
[  184.773970] i915 0000:00:02.0: [drm] GT0: IOV: Failed to save VF7 state (-EPROTO)
[  213.152942] i915 0000:00:02.0: [drm] *ERROR* GT0: GUC: CT: Sending action 0x550b failed (-EIO) status=0XE0000102
[  213.152953] i915 0000:00:02.0: [drm] GT0: IOV: Failed to save VF1 state (-EPROTO)
[  213.153168] i915 0000:00:02.0: [drm] *ERROR* GT0: GUC: CT: Sending action 0x550b failed (-EIO) status=0XE0000102
[  213.153171] i915 0000:00:02.0: [drm] GT0: IOV: Failed to save VF2 state (-EPROTO)
[  213.153359] i915 0000:00:02.0: [drm] *ERROR* GT0: GUC: CT: Sending action 0x550b failed (-EIO) status=0XE0000102
[  213.153362] i915 0000:00:02.0: [drm] GT0: IOV: Failed to save VF3 state (-EPROTO)
[  213.153527] i915 0000:00:02.0: [drm] *ERROR* GT0: GUC: CT: Sending action 0x550b failed (-EIO) status=0XE000000A
[  213.153529] i915 0000:00:02.0: [drm] GT0: IOV: Failed to save VF4 state (-EPROTO)
[  213.153714] i915 0000:00:02.0: [drm] *ERROR* GT0: GUC: CT: Sending action 0x550b failed (-EIO) status=0XE0000102
[  213.153717] i915 0000:00:02.0: [drm] GT0: IOV: Failed to save VF5 state (-EPROTO)
[  213.154050] i915 0000:00:02.0: [drm] *ERROR* GT0: GUC: CT: Sending action 0x550b failed (-EIO) status=0XE0000102
[  213.154053] i915 0000:00:02.0: [drm] GT0: IOV: Failed to save VF6 state (-EPROTO)
[  213.154249] i915 0000:00:02.0: [drm] *ERROR* GT0: GUC: CT: Sending action 0x550b failed (-EIO) status=0XE0000102
[  213.154252] i915 0000:00:02.0: [drm] GT0: IOV: Failed to save VF7 state (-EPROTO)
[  267.090588] i915 0000:00:02.0: VF4 FLR

At the same time, the system seems to see that the Intel XE iGPU is installed, because
root@server:/dev/dri# ls
by-path  card0  card1  card2  card3  card5  card6  card7  renderD128  renderD129  renderD130  renderD131  renderD133  renderD134  renderD135

But when running LXC emby and others, transcoding is performed at the expense of the CPU, I checked “intel_gpu_top” all indicators are 0% during active viewing. 
Well, when trying to start the VM there was also no luck, error 43 in the VM. But in view of the log above, I am still inclined that the problem is on the host, it does not initialize the video card correctly 
The system is built on a Chinese motherboard with a built-in Core i7-1280P processor, all virtualization is enabled in the BIOS, secure boot is disabled.

root@server:~ apt list -a intel-microcode
Listing... Done
intel-microcode/now 3.20241112.1 amd64 [installed,local]
intel-microcode/stable 3.20240910.1~deb12u1 amd64

Kernel Version Linux 6.8.12-4-pve (2024-11-06T15:04Z)
Boot Mode EFI
Manager Version pve-manager/8.3.0/

Here (https://www.amrzs.net/2024/11/03/pve_sriov_gpu/) a person had similar problems after installing i915-sriov-dkms, and he installed intel-gpu-i915-backports, but I did the same I tried this, iGPU initialization in i915-sriov-dkms breaks down with freeze messages

I am ready to provide any information to solve this problem =) Thank you

**Comment by bbaa-bbaa** [comment]
Have you ever tried to update your motherboard BIOS?

**Comment by sacredx72** [comment]
@bbaa-bbaa 
No, I didn’t update the BIOS on this board, judging by the logs there is a problem with addressing at the hardware hardware level?

**Comment by bbaa-bbaa** [comment]
> [ 23.461515] i915 0000:00:02.7: [drm] ERROR GT0: Failed to retrieve hwconfig table: -ENOENT

Maybe your BIOS missing hwconfig table?
Can you try to update your BIOS?

**Comment by bbaa-bbaa** [comment]
Besides, the MMIO seems to be related to the bios setting `Resizable BAR`. Can you check it is enabled?

**Comment by sacredx72** [comment]
Ok, I will request a new bios from the manufacturer and return after checking.
It’s strange, but when I started from another hard drive where Windows 10 host was installed, I didn’t notice any problems with the drivers or iGPU operation =) But it’s worth checking the BIOS
Resizable BAR is included in the BIOS, I checked it right away

**Comment by resiliencer** [comment]
@sacredx72 
Hmm, I have it in the kernel logs too:  `GuC firmware PRELOADED version 0.0`
but it doesn't seem to be a problem
